########################################
########## DEPRECATION NOTICE ##########
########################################
# This app will be deprecated soon.
# Reasons: 
#   - Config has not been tested properly
#   - Of questionable use as-is
#   - Might be integrated again after testing and rework

# docker run -it --name my-running-irssi -e TERM -u $(id -u):$(id -g) \
#     --log-driver=none \
#     -v $HOME/.irssi:/home/user/.irssi:ro \
#     -v /etc/localtime:/etc/localtime:ro \
#     irssi

version: '3.3'

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  irssi-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/irssi/database/
  irssi-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/irssi/data

  irssi-app:
    container_name: irssi-app
    image: irssi:1.2.2-alpine
    security_opt:
      - no-new-privileges:true
    volumes:
      - $HOME/.irssi:/home/user/.irssi:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - irssi-db
    environment:
      - TERM
    labels:
      - traefik.enable=true
      - traefik.http.routers.irssi-app-secure.entrypoints=websecure
      - traefik.http.routers.irssi-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.irssi-app-secure.tls=true
      - traefik.http.routers.irssi-app-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.irssi-app-secure.service=irssi-app
      - traefik.http.routers.irssi-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.irssi-app.loadbalancer.server.port=3000
    networks:
      - proxy
      - internal
    ports:
      - "222:22"
    restart: unless-stopped