name: irssi

networks:
  proxy:
    name: proxy
    external: true

volumes:
  irssi-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/irssi/data

services:
  irssi-app:
    container_name: irssi-app
    image: irssi:alpine
    security_opt:
      - no-new-privileges:true
    environment:
      - TERM=xterm
    user: ${PUID}:${PGID}
    volumes:
      - irssi-data:/home/user/.irssi:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      - traefik.enable=false
    tty: true
    stdin_open: true
    restart: unless-stopped
