version: '3.5'

networks:
    proxy:
      external: 
        name: proxy
    internal:
      internal: true

services:
  drawio-app:
    container_name: drawio-app
    image: jgraph/drawio
    security_opt:
      - no-new-privileges:true
    environment:
      PUBLIC_DNS: ${SUBDOMAIN}.${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio-app.entrypoints=http"
      - "traefik.http.routers.drawio-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.drawio-app.middlewares=secured@file"
      - "traefik.http.routers.drawio-app-secure.entrypoints=https"
      - "traefik.http.routers.drawio-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.drawio-app-secure.tls=true"
      - "traefik.http.routers.drawio-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.drawio-app-secure.service=drawio-app"
      - "traefik.http.services.drawio-app.loadbalancer.server.port=8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - internal
      - proxy
    restart: unless-stopped
