version: "3.3"

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  statping-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/statping/database/
  statping-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/statping/data

services:
  statping-db:
    container_name: statping-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=statping
      - MYSQL_USER=statping
      - MYSQL_PASSWORD=${DB_USER_PASS}
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    volumes:
      - statping-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  statping-app:
    container_name: statping-app
    image: adamboutcher/statping-ng:latest
    security_opt:
      - no-new-privileges:true
    depends_on:
      - statping-db
    volumes:
      - statping-data:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_CONN: mysql
      DB_HOST: statping-db
      DB_USER: statping
      DB_PASS: ${DB_USER_PASS}
      DB_DATABASE: statping
      DB_PORT: 3306
      API_SECRET: exampleapisecret
      NAME: ${DOMAIN} Status
      DOMAIN: https://${SUBDOMAIN}.${DOMAIN}
      DESCRIPTION: Current service status
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASS}
      SAMPLE_DATA: 'false'
    labels:
      - traefik.enable=true
      - traefik.http.routers.statping-app-secure.entrypoints=websecure
      - traefik.http.routers.statping-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.statping-app-secure.tls=true
      - traefik.http.routers.statping-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.statping-app-secure.service=statping-app
      - traefik.http.routers.statping-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.statping-app.loadbalancer.server.port=8080
    networks:
      - internal
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || false"]
      timeout: 2s
      interval: 10s
      retries: 20
    restart: unless-stopped