version: "3.3"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  cryptofolio-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/cryptofolio/data

services:
  cryptofolio-app:
    container_name: cryptofolio-app
    image: xtrendence/cryptofolio:V.2.0.0
    security_opt:
      - no-new-privileges:true
    volumes:
      - cryptofolio-data:/var/www/html/api/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.cryptofolio.entrypoints=http
      - traefik.http.routers.cryptofolio.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.cryptofolio-secure.entrypoints=https
      - traefik.http.routers.cryptofolio-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.cryptofolio-secure.tls=true
      - traefik.http.routers.cryptofolio-secure.tls.certresolver=le-dns
      - traefik.http.routers.cryptofolio-secure.service=cryptofolio
      - traefik.http.routers.cryptofolio-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.cryptofolio.loadbalancer.server.port=80
    networks:
      - proxy
    restart: unless-stopped