version: "3.8"

networks:
  proxy:
    name: proxy
    external: true

services:
  excalidraw:
    container_name: excalidraw
    image:  excalidraw/excalidraw:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.entrypoints=web
      - traefik.http.routers.excalidraw.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.excalidraw-secure.entrypoints=websecure
      - traefik.http.routers.excalidraw-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.excalidraw-secure.tls=true
      - traefik.http.routers.excalidraw-secure.tls.certresolver=le-dns
      - traefik.http.routers.excalidraw-secure.service=excalidraw
      - traefik.http.routers.excalidraw-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    networks:
      - proxy
    restart: unless-stopped