name: jackett

networks:
  proxy:
    name: proxy
    external: true

volumes:
  jackett-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/jackett/config
  jackett-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/jackett/downloads

services:
  jackett:
    container_name: jackett
    image: ghcr.io/linuxserver/jackett:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett-secure.entrypoints=websecure
      - traefik.http.routers.jackett-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.jackett-secure.tls=true
      - traefik.http.routers.jackett-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.jackett-secure.service=jackett
      - traefik.http.routers.jackett-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.jackett.loadbalancer.server.port=9117
    networks:
      - proxy
    restart: unless-stopped
