version: "3"

networks:
  proxy:
    external: 
      name: proxy

volumes:
  baikal-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/baikal/config
  baikal-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/baikal/data

services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    security_opt:
      - no-new-privileges:true
    volumes:
      - baikal-config:/var/www/baikal/config
      - baikal-data:/var/www/baikal/Specific
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.entrypoints=http"
      - "traefik.http.routers.baikal.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.baikal.middlewares=secured@file"
      - "traefik.http.routers.baikal-secure.entrypoints=https"
      - "traefik.http.routers.baikal-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.baikal-secure.tls=true"
      - "traefik.http.routers.baikal-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.baikal-secure.service=baikal"
      - "traefik.http.services.baikal.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped
