name: ntfy

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  ntfy-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/ntfy/config
  ntfy-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/ntfy/cache

services:
  ntfy-app:
    container_name: ntfy-app
    image: binwiederhier/ntfy
    security_opt:
      - no-new-privileges:true
    command:
      - serve
    environment:
      - TZ=${TIMEZONE}
    user: ${PUID}:${PGID}
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-config:/etc/ntfy
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy-app-secure.entrypoints=websecure
      - traefik.http.routers.ntfy-app-secure.rule=Host(`${SUBDOMAIN:+${SUBDOMAIN}.}${DOMAIN}`)
      - traefik.http.routers.ntfy-app-secure.tls=true
      - traefik.http.routers.ntfy-app-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.ntfy-app-secure.service=ntfy-app
      - traefik.http.routers.ntfy-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.ntfy-app.loadbalancer.server.port=80
    restart: unless-stopped