version: '3.9'

networks:
  proxy:
    name: proxy
    external: true

services:
  web-check-app:
    container_name: web-check-app
    image: lissy93/web-check
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-check-app.entrypoints=web
      - traefik.http.routers.web-check-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.web-check-app-secure.entrypoints=websecure
      - traefik.http.routers.web-check-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.web-check-app-secure.tls=true
      - traefik.http.routers.web-check-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.web-check-app-secure.service=web-check-app
      - traefik.http.routers.web-check-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.web-check-app.loadbalancer.server.port=3000
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    networks:
      - proxy
    restart: unless-stopped