name: homeassistant-addons-whisper

volumes:
  ha-whisper-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/homeassistant/whisper/data

services:
  ha-whisper:
    container_name: ha-whisper
    image: rhasspy/wyoming-whisper:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - ha-whisper-data:/data
      - /etc/localtime:/etc/localtime:ro
    command: [ "--model", "tiny-int8", "--language", "en" ]
    labels:
      - "traefik.enable=false"
    ports:
      - "10300:10300"
    restart: unless-stopped