version: "2"

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  youtube-dl-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/youtube-dl/database

  youtube-dl-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/youtube-dl/data

  youtube-dl-audio:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/youtube-dl/downloads/audio

  youtube-dl-video:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/youtube-dl/downloads/video

  youtube-dl-subscriptions:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/youtube-dl/downloads/subscriptions

  youtube-dl-users:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/youtube-dl/downloads/users

services:
  youtube-dl-db:
    container_name: youtube-dl-db
    image: mongo:latest
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "none"          
    volumes:
      - youtube-dl-database:/data/db
    networks:
      - internal
    restart: unless-stopped

  youtube-dl-material:
    container_name: youtube-dl-material
    image: tzahi12345/youtubedl-material:latest
    security_opt:
      - no-new-privileges:true
    environment: 
      UID: ${PUID}
      GID: ${PGID}
      ytdl_mongodb_connection_string: 'mongodb://youtube-dl-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
    depends_on:
      - youtube-dl-db
    volumes:
      - youtube-dl-data:/app/appdata
      - youtube-dl-audio:/app/audio
      - youtube-dl-video:/app/video
      - youtube-dl-subscriptions:/app/subscriptions
      - youtube-dl-users:/app/users
    labels:
      - traefik.enable=true
      - traefik.http.routers.youtube-dl-material.entrypoints=http
      - traefik.http.routers.youtube-dl-material.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.youtube-dl-material-secure.entrypoints=https
      - traefik.http.routers.youtube-dl-material-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.youtube-dl-material-secure.tls=true
      - traefik.http.routers.youtube-dl-material-secure.tls.certresolver=le-dns
      - traefik.http.routers.youtube-dl-material-secure.service=youtube-dl-material
      - traefik.http.routers.youtube-dl-material-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.youtube-dl-material.loadbalancer.server.port=17442
    networks:
      - internal
      - proxy
    restart: unless-stopped
