name: bitmagnet

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  bitmagnet-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/bitmagnet/database

services:
  bitmagnet-db:
    container_name: bitmagnet-db
    image: postgres:16-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    volumes:
      - bitmagnet-database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=${DB_USER_PASS}
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s
    restart: unless-stopped

  bitmagnet-app:
    container_name: bitmagnet-app
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
      - proxy
    ports:
      # BitTorrent ports:
      - "3334:3334/tcp"
      - "3334:3334/udp"
    environment:
      - POSTGRES_HOST=bitmagnet-db
      - POSTGRES_PASSWORD=${DB_USER_PASS}
      # - TMDB_API_KEY=your_api_key
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      # disable the next line to run without DHT crawler
      - --keys=dht_crawler
    depends_on:
      bitmagnet-db:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.bitmagnet-secure.entrypoints=websecure
      - traefik.http.routers.bitmagnet-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.bitmagnet-secure.tls=true
      - traefik.http.routers.bitmagnet-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.bitmagnet-secure.service=bitmagnet
      - traefik.http.routers.bitmagnet-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.bitmagnet.loadbalancer.server.port=3333
    restart: unless-stopped