version: "3.3"
networks:
  proxy:
    name: proxy
    external: true

services:
  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.openspeedtest.entrypoints=http
      - traefik.http.routers.openspeedtest.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.openspeedtest-secure.entrypoints=https
      - traefik.http.routers.openspeedtest-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.openspeedtest-secure.tls=true
      - traefik.http.routers.openspeedtest-secure.tls.certresolver=le-dns
      - traefik.http.routers.openspeedtest-secure.service=openspeedtest
      - traefik.http.routers.openspeedtest-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.openspeedtest.loadbalancer.server.port=8080
    restart: unless-stopped