name: node-red

networks:
  proxy:
    name: proxy
    external: true

volumes:
  nodered-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/node-red/data
  # nodered-download-dir:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${DOCKER_ROOT}/downloads/complete
      

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest-minimal
    restart: always
    user: root
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - nodered-data:/data
      - /etc/localtime:/etc/localtime:ro
      # - nodered-download-dir:/storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.nodered-secure.entrypoints=websecure
      - traefik.http.routers.nodered-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.nodered-secure.tls=true
      - traefik.http.routers.nodered-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.nodered-secure.service=nodered
      - traefik.http.routers.nodered-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.nodered.loadbalancer.server.port=1880
    networks:
      - proxy