name: metube

networks:
  proxy:
    name: proxy
    external: true

volumes:
  metube-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/metube/downloads

services:
  metube-app:
    container_name: metube-app
    image: ghcr.io/alexta69/metube
    security_opt:
      - no-new-privileges:true
    volumes:
      - metube-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - DEFAULT_THEME=dark
      - DELETE_FILE_ON_TRASHCAN=true
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.metube-app-secure.entrypoints=websecure
      - traefik.http.routers.metube-app-secure.rule=Host(`${SUBDOMAIN:+${SUBDOMAIN}.}${DOMAIN}`)
      - traefik.http.routers.metube-app-secure.tls=true
      - traefik.http.routers.metube-app-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.metube-app-secure.service=metube-app
      - traefik.http.routers.metube-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.metube-app.loadbalancer.server.port=8081
    restart: unless-stopped
