version: '3'

networks:
  proxy:
    name: proxy
    external: true

volumes:
  flame-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/flame/data

services:
  flame:
    container_name: flame
    image: pawelmalak/flame:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - flame-data:/app/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.flame-secure.entrypoints=websecure
      - traefik.http.routers.flame-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.flame-secure.tls=true
      - traefik.http.routers.flame-secure.tls.certresolver=le-dns
      - traefik.http.routers.flame-secure.service=flame
      - traefik.http.routers.flame-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.flame.loadbalancer.server.port=5005
    networks:
      - proxy
    restart: unless-stopped
