version: '3'

networks:
  proxy:
    name: proxy
    external: true

volumes:
  searx-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/searx/config

services:
  searx-app:
    container_name: searx-app
    image: searx/searx:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - BASE_URL=https://${SUBDOMAIN}.${DOMAIN}
    volumes:
      - searx-config:/etc/searx
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.searx-app.entrypoints=http
      - traefik.http.routers.searx-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.searx-app-secure.entrypoints=https
      - traefik.http.routers.searx-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.searx-app-secure.tls=true
      - traefik.http.routers.searx-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.searx-app-secure.service=searx-app
      - traefik.http.routers.searx-app-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.searx-app.loadbalancer.server.port=8080
    networks:
      - proxy
    restart: unless-stopped
