version: '3'

# networks:
#   proxy:
#     name: proxy
#     external: true

volumes:
  lidarr-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/lidarr/config
  lidarr-music-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MUSIC_PATH}
  lidarr-downloads-dir:
    driver: local
    driver_opts:
      type: ${DOWNLOADS_DRIVER_OPT_TYPE}
      o: ${DOWNLOADS_DRIVER_OPT_O}
      device: ${DOWNLOADS_PATH}

services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/linuxserver/lidarr:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - lidarr-config:/config
      - lidarr-music-dir:/music
      - lidarr-downloads-dir:/downloads
      - /etc/localtime:/etc/localtime:ro
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.lidarr.entrypoints=http"
    #   - "traefik.http.routers.lidarr.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.lidarr.middlewares=secured@file"
    #   - "traefik.http.routers.lidarr-secure.entrypoints=https"
    #   - "traefik.http.routers.lidarr-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.lidarr-secure.tls=true"
    #   - "traefik.http.routers.lidarr-secure.tls.certresolver=le-dns"
    #   - "traefik.http.routers.lidarr-secure.service=lidarr"
    #   - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
    # networks:
    #   - proxy
    labels:
      - "traefik.enable=false"
    network_mode: container:expressvpn
    restart: unless-stopped