version: '3'

networks:
  proxy:
    name: proxy
    external: true

volumes:
  pwndrop-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/pwndrop/config

services:
  pwndrop-app:
    container_name: pwndrop-app
    image: ghcr.io/linuxserver/pwndrop:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - SECRET_PATH=/pwndrop #optional
    volumes:
      - pwndrop-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.pwndrop-app.entrypoints=web
      - traefik.http.routers.pwndrop-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.pwndrop-app-secure.entrypoints=websecure
      - traefik.http.routers.pwndrop-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.pwndrop-app-secure.tls=true
      - traefik.http.routers.pwndrop-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.pwndrop-app-secure.service=pwndrop-app
      - traefik.http.routers.pwndrop-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.pwndrop-app.loadbalancer.server.port=8080
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    networks: 
      - proxy
    restart: unless-stopped