name: wireshark

networks:
  proxy:
    name: proxy
    external: true

volumes:
  wireshark-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/wireshark/config

services:
  wireshark-app:
    container_name: wireshark-app
    image: ghcr.io/linuxserver/wireshark:latest
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - wireshark-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    restart: unless-stopped
