name: beszel-agent

services:
  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PORT=45876
      - KEY=${KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "45876:45876/tcp"
    restart: unless-stopped