name: beszel-agent

networks:
  proxy:
    name: proxy
    external: true

services:
  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PORT=45876
      - KEY=${KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel-agent-secure.entrypoints=websecure
      - traefik.http.routers.beszel-agent-secure.rule=Host(`${SUBDOMAIN:+${SUBDOMAIN}.}${DOMAIN}`)
      - traefik.http.routers.beszel-agent-secure.tls=true
      - traefik.http.routers.beszel-agent-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.beszel-agent-secure.service=beszel-agent
      - traefik.http.routers.beszel-agent-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.beszel-agent.loadbalancer.server.port=45876
    networks:
      - proxy
    restart: unless-stopped