name: searcx-ng

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  searxng-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/searxng/config
  searxng-valkey:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/searxng/valkey

services:
  searxng-app:
    container_name: searxng-app
    image: searxng/searxng:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - SEARXNG_BASE_URL=https://${SUBDOMAIN}.${DOMAIN}
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_VALKEY_URL=valkey://searxng-valkey:6379/0
      - SEARXNG_IMAGE_PROXY=${SEARXNG_IMAGE_PROXY:-true}
      - SEARXNG_LIMITER=${SEARXNG_LIMITER:-false}
      - SEARXNG_METHOD=${SEARXNG_METHOD:-POST}
    volumes:
      - searxng-config:/etc/searxng
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.searxng-app-secure.entrypoints=websecure
      - traefik.http.routers.searxng-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.searxng-app-secure.tls=true
      - traefik.http.routers.searxng-app-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.searxng-app-secure.service=searxng-app
      - traefik.http.routers.searxng-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.searxng-app.loadbalancer.server.port=8080
    networks:
      - internal
      - proxy
    depends_on:
      searxng-valkey:
        condition: service_healthy
    restart: unless-stopped

  searxng-valkey:
    container_name: searxng-valkey
    image: valkey/valkey:8-alpine
    security_opt:
      - no-new-privileges:true
    command: valkey-server --save 30 1 --loglevel warning
    networks:
      - internal
    volumes:
      - searxng-valkey:/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    labels:
      - "traefik.enable=false"
    restart: unless-stopped
