version: '3'

# networks:
#   proxy:
#     name: proxy
#     external: true
#   internal:
#     internal: true

volumes:
  romm-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/romm/database/
  romm-resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/romm/resources
  romm-roms-dir:
    driver: local
    driver_opts:
      type: ${MEDIA_DRIVER_OPT_TYPE}
      o: ${MEDIA_DRIVER_OPT_O}
      device: ${ROMS_PATH}

services:
  romm-db:
    container_name: romm-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    # networks:
    #   - internal
    network_mode: container:expressvpn
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=romm
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - romm-database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  romm-app:
    container_name: romm-app
    image: 'zurdi15/romm:latest'
    security_opt:
      - no-new-privileges:true
    environment:
      - ROMM_DB_DRIVER="mariadb"
      - DB_HOST=romm-db
      - DB_PORT=3306
      - DB_USER=romm
      - DB_NAME=${DB_NAME}
      - DB_PASSWD=${DB_USER_PASS}
      - CLIENT_ID=${IGDB_CLIENT_ID}
      - CLIENT_SECRET=${IGDB_CLIENT_SECRET}
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY}
    volumes:
      - 'romm-roms-dir:/romm/library'
      - 'romm-resources:/romm/resources'
      - '${DOCKER_ROOT}/romm/config/config.yml:/romm/config.yml'
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
      # - "traefik.enable=true"
      # - "traefik.http.routers.romm.entrypoints=http"
      # - "traefik.http.routers.romm.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      # - "traefik.http.routers.romm.middlewares=secured@file"
      # - "traefik.http.routers.romm-secure.entrypoints=https"
      # - "traefik.http.routers.romm-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      # - "traefik.http.routers.romm-secure.tls=true"
      # - "traefik.http.routers.romm-secure.tls.certresolver=le-dns"
      # - "traefik.http.routers.romm-secure.service=romm"
      # - "traefik.http.services.romm.loadbalancer.server.port=80"
    depends_on:
      - romm-db
    # networks:
    #   - internal
    #   - proxy
    # ports:
    #   - 5959:80
    network_mode: container:expressvpn
    restart: unless-stopped
