version: '3.3'

networks:
  proxy:
    external: 
      name: proxy

services:

  hugo-site-1:
    container_name: "hugo-site-1"
    image: "jojomi/nginx-static"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./output:/var/www
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hugo-site-1.entrypoints=http"
      - "traefik.http.routers.hugo-site-1.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.hugo-site-1.middlewares=secured@file"
      - "traefik.http.routers.hugo-site-1-secure.entrypoints=https"
      - "traefik.http.routers.hugo-site-1-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.hugo-site-1-secure.tls=true"
      - "traefik.http.routers.hugo-site-1-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.hugo-site-1-secure.service=hugo-site-1"
      - "traefik.http.services.hugo-site-1.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped
