version: '3'

networks:
  proxy:
    external:
      name: proxy

volumes:
  radarr-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/radarr/config
  radarr-movies-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/video/movies
  radarr-downloads-dir:
    driver: local
    driver_opts:
      type: ${DOWNLOADS_DRIVER_OPT_TYPE}
      o: ${DOWNLOADS_DRIVER_OPT_O}
      device: ${DOWNLOADS_PATH}

services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022 #optional
    volumes:
      - radarr-config:/config
      - radarr-movies-dir:/movies
      - radarr-downloads-dir:/downloads
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.radarr.entrypoints=http"
    #   - "traefik.http.routers.radarr.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.radarr.middlewares=secured@file"
    #   - "traefik.http.routers.radarr-secure.entrypoints=https"
    #   - "traefik.http.routers.radarr-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
    #   - "traefik.http.routers.radarr-secure.tls=true"
    #   - "traefik.http.routers.radarr-secure.tls.certresolver=le-dns"
    #   - "traefik.http.routers.radarr-secure.service=radarr"
    #   - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    # networks:
    #   - proxy
    labels:
      - "traefik.enable=false"
    network_mode: container:expressvpn
    restart: unless-stopped