version: "3.4"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  chat-with-gpt-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/chat-with-gpt/data

services:
  chat-with-gpt-app:
    container_name: chat-with-gpt
    image: ghcr.io/cogentapps/chat-with-gpt:release
    security_opt:
      - no-new-privileges:true
    volumes:
      - chat-with-gpt-data:/app/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.chat-with-gpt-app.entrypoints=web
      - traefik.http.routers.chat-with-gpt-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.chat-with-gpt-app-secure.entrypoints=websecure
      - traefik.http.routers.chat-with-gpt-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.chat-with-gpt-app-secure.tls=true
      - traefik.http.routers.chat-with-gpt-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.chat-with-gpt-app-secure.service=chat-with-gpt-app
      - traefik.http.routers.chat-with-gpt-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.chat-with-gpt-app.loadbalancer.server.port=3000
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    networks: 
      - proxy
    restart: unless-stopped
