version: "2.1"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  transmission-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/transmission/config
  transmission-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads
  transmission-watchdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/transmission/watch

services:
  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      # - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
      - transmission-watchdir:/watch
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission-secure.entrypoints=websecure
      - traefik.http.routers.transmission-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.transmission-secure.tls=true
      - traefik.http.routers.transmission-secure.tls.certresolver=le-dns
      - traefik.http.routers.transmission-secure.service=transmission
      - traefik.http.routers.transmission-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.transmission.loadbalancer.server.port=9091
    networks:
      - proxy
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
