name: tdarr

networks:
  proxy:
    name: proxy
    external: true

volumes:
  tdarr-configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/tdarr/configs
  tdarr-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/tdarr/data
  tdarr-series-dir:
    driver: local
    driver_opts:
      type: ${MEDIA_DRIVER_OPT_TYPE}
      o: ${MEDIA_DRIVER_OPT_O}
      device: ${SERIES_PATH}
  tdarr-movies-dir:
    driver: local
    driver_opts:
      type: ${MEDIA_DRIVER_OPT_TYPE}
      o: ${MEDIA_DRIVER_OPT_O}
      device: ${MOVIES_PATH}

services:
  tdarr-server:
    container_name: tdarr-server
    image: ghcr.io/haveagitgat/tdarr:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - 8266:8266 # server port
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # - NVIDIA_VISIBLE_DEVICES=all
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr-server-secure.entrypoints=websecure
      - traefik.http.routers.tdarr-server-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.tdarr-server-secure.tls=true
      - traefik.http.routers.tdarr-server-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.tdarr-server-secure.service=tdarr-server
      - traefik.http.routers.tdarr-server-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.tdarr-server.loadbalancer.server.port=8265
    networks:
      - proxy
    volumes:
      - tdarr-data:/app/server
      - tdarr-configs:/app/configs
      - tdarr-movies-dir:/media/movies
      - tdarr-series-dir:/media/series
      - ./logs:/app/logs
      - ./transcode_cache:/temp
      - /etc/localtime:/etc/localtime:ro
    # devices:
    #   - /dev/dri:/dev/dri
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: amd
    #         count: all
    #         capabilities: [gpu]
    restart: unless-stopped
    

  # # node example
  # tdarr-node:
  #   container_name: tdarr-node
  #   image: ghcr.io/haveagitgat/tdarr_node:latest
  #   network_mode: service:tdarr
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - UMASK_SET=002
  #     - nodeName=MyExternalNode
  #     - serverIP=0.0.0.0
  #     - serverPort=8266
  #     - inContainer=true
  #     - ffmpegVersion=6
  #     # - NVIDIA_DRIVER_CAPABILITIES=all
  #     # - NVIDIA_VISIBLE_DEVICES=all
  #   volumes:
      # - tdarr-configs:/app/configs
      # - tdarr-movies-dir:/media/movies
      # - tdarr-series-dir:/media/series
      # - ./logs:/app/logs
      # - ./transcode_cache:/temp
      # - /etc/localtime:/etc/localtime:ro
  #   devices:
  #     - /dev/dri:/dev/dri
  # # deploy:
  # #   resources:
  # #     reservations:
  # #       devices:
  # #       - driver: nvidia
  # #         count: all
  # #         capabilities: [gpu]    
  #   restart: unless-stopped