name: Uptime-Kuma

networks:
  proxy:
    name: proxy
    external: true

volumes:
  uptime-kuma-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/uptime-kuma/data

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1-alpine
    security_opt:
      - no-new-privileges:true
    volumes:
      - uptime-kuma-data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma-secure.entrypoints=websecure
      - traefik.http.routers.uptime-kuma-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.uptime-kuma-secure.tls=true
      - traefik.http.routers.uptime-kuma-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.uptime-kuma-secure.service=uptime-kuma
      - traefik.http.routers.uptime-kuma-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
    networks:
      - proxy
    restart: always
