version: '3.8'

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  ollama-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/ollama/data
  ollama-ui:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/ollama/ui

services:
  ollama-backend:
    container_name: ollama-backend
    image: ollama/ollama:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - ollama-data:/root/.ollama
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.ollama-backend.entrypoints=web
      - traefik.http.routers.ollama-backend.rule=Host(`backend.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.ollama-backend-secure.entrypoints=websecure
      - traefik.http.routers.ollama-backend-secure.rule=Host(`backend.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.ollama-backend-secure.tls=true
      - traefik.http.routers.ollama-backend-secure.tls.certresolver=le-dns
      - traefik.http.routers.ollama-backend-secure.service=ollama-backend
      - traefik.http.routers.ollama-backend-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.ollama-backend.loadbalancer.server.port=11434
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    networks:
      - internal
      - proxy
    restart: unless-stopped

  ollama-webui:
    container_name: ollama-webui
    image: ghcr.io/ollama-webui/ollama-webui:main
    security_opt:
      - no-new-privileges:true
    volumes:
      - ollama-ui:/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama-backend:11434/api'
    depends_on:
      - ollama-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.ollama-webui.entrypoints=web
      - traefik.http.routers.ollama-webui.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.ollama-webui-secure.entrypoints=websecure
      - traefik.http.routers.ollama-webui-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.ollama-webui-secure.tls=true
      - traefik.http.routers.ollama-webui-secure.tls.certresolver=le-dns
      - traefik.http.routers.ollama-webui-secure.service=ollama-webui
      - traefik.http.routers.ollama-webui-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.ollama-webui.loadbalancer.server.port=8080
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    networks:
      - internal
      - proxy
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    restart: unless-stopped