version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:
  wp-db:
    container_name: "wp-${COMPOSE_PROJECT_NAME}-db"
    image: "mariadb"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${DB_USER_PASS}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  wp-app:
    container_name: "wp-${COMPOSE_PROJECT_NAME}-app"
    image: "wordpress:php7.4-fpm-alpine"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wp-db
    environment:
      - WORDPRESS_DB_HOST=wp-db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${DB_USER_PASS}
    volumes:
      - wordpress:/var/www/html
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/plugins:/var/www/html/wp-content/plugins/
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/themes:/var/www/html/wp-content/themes/
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/uploads:/var/www/html/wp-content/uploads/
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - proxy
      - internal
    restart: unless-stopped


  wp-nginx:
    container_name: "wp-${COMPOSE_PROJECT_NAME}-nginx"
    image: "nginx:alpine"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wp-app
    networks:
      - internal
      - proxy
    volumes:
      - wordpress:/var/www/html:ro
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/plugins:/var/www/html/wp-content/plugins/:ro
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/themes:/var/www/html/wp-content/themes/:ro
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/uploads:/var/www/html/wp-content/uploads/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.entrypoints=http"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.middlewares=secured@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.service=${COMPOSE_PROJECT_NAME}-nginx"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-nginx.loadbalancer.server.port=80"
    restart: unless-stopped

volumes:
  wordpress:
  wp-db: