name: PiHole

networks:
  proxy:
    name: proxy
    external: true

volumes:
  pihole-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/pihole/etc/
  piho${CERT_RESOLVER}masq:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/pihole/dnsmasq/

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${ADMIN_PASS}
      - VIRTUAL_HOST=https://${SUBDOMAIN}.${DOMAIN}
      - PIHOLE_DNS_=127.0.0.1;1.1.1.1;1.0.0.1
    volumes:
      - 'pihole-config:/etc/pihole/'
      - 'piho${CERT_RESOLVER}masq:/etc/dnsmasq.d/'
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole-secure.entrypoints=websecure
      - traefik.http.routers.pihole-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.pihole-secure.tls=true
      - traefik.http.routers.pihole-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.pihole-secure.service=pihole
      - traefik.http.routers.pihole-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.pihole.loadbalancer.server.port=80
    networks:
      - proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
