version: "3.3"

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  matomo-app:
  matomo-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matomo/database
  matomo-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matomo/config

services:
  matomo-db:
    container_name: matomo-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - matomo-database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  matomo-app:
    container_name: "matomo-app"
    image: "matomo:fpm-alpine"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - matomo-db
    volumes:
      - matomo-config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo-app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=${DB_USER_PASS}
      - MATOMO_DATABASE_DBNAME=matomo
    restart: unless-stopped


  matomo-nginx:
    container_name: "matomo-nginx"
    image: "nginx:alpine"
    security_opt:
      - no-new-privileges:true
    volumes:
      - matomo-app:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo-nginx.entrypoints=http"
      - "traefik.http.routers.matomo-nginx.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.matomo-nginx.middlewares=secured@file"
      - "traefik.http.routers.matomo-nginx-secure.entrypoints=https"
      - "traefik.http.routers.matomo-nginx-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.matomo-nginx-secure.tls=true"
      - "traefik.http.routers.matomo-nginx-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.matomo-nginx-secure.service=matomo-nginx"
      - "traefik.http.services.matomo-nginx.loadbalancer.server.port=80"
    networks:
      - proxy
      - internal
    restart: unless-stopped
