version: '3'

networks:
  proxy:
    name: proxy
    external: true

volumes:
  thelounge-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/thelounge/config

services:
  thelounge:
    container_name: thelounge
    image: ghcr.io/linuxserver/thelounge:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - thelounge-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thelounge.entrypoints=http"
      - "traefik.http.routers.thelounge.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.thelounge.middlewares=secured@file"
      - "traefik.http.routers.thelounge-secure.entrypoints=https"
      - "traefik.http.routers.thelounge-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.thelounge-secure.tls=true"
      - "traefik.http.routers.thelounge-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.thelounge-secure.service=thelounge"
      - "traefik.http.services.thelounge.loadbalancer.server.port=9000"
    networks:
      - proxy
    # # Used for SSH remoteForward
    # ports:
    #   - 4005:9000
    restart: unless-stopped