name: TheLounge

networks:
  proxy:
    name: proxy
    external: true

volumes:
  thelounge-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/thelounge/config

services:
  thelounge:
    container_name: thelounge
    image: ghcr.io/linuxserver/thelounge:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - thelounge-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.thelounge-secure.entrypoints=websecure
      - traefik.http.routers.thelounge-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.thelounge-secure.tls=true
      - traefik.http.routers.thelounge-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.thelounge-secure.service=thelounge
      - traefik.http.routers.thelounge-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.thelounge.loadbalancer.server.port=9000
    networks:
      - proxy
    # # Used for SSH remoteForward
    # ports:
    #   - 4005:9000
    restart: unless-stopped