version: "2.1"

volumes:
  nzbget-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/docker/nzbget/config
  nzbget-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads

services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - nzbget-config:/config
      - nzbget-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:expressvpn
    restart: unless-stopped