version: "3.9"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  frigate-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/frigate/config
  frigate-footage:
    driver: local
    driver_opts:
      type: ${FOOTAGE_DRIVER_OPT_TYPE}
      o: ${FOOTAGE_DRIVER_OPT_O}
      device: ${FOOTAGE_PATH}

services:
  frigate-app:
    container_name: frigate-app
    image: ghcr.io/blakeblackshear/frigate:stable
    # privileged: true # this may not be necessary for all setups
    security_opt:
      - no-new-privileges:true
    shm_size: "64mb" # update for your cameras based on calculation above
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/video11:/dev/video11  # For Raspberry Pi 4B
    #   - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    environment:
      FRIGATE_RTSP_PASSWORD: ${RTSP_PASS}
    volumes:
      - frigate-config:/config
      - frigate-footage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.frigate-app.entrypoints=web
      - traefik.http.routers.frigate-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.frigate-app-secure.entrypoints=websecure
      - traefik.http.routers.frigate-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.frigate-app-secure.tls=true
      - traefik.http.routers.frigate-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.frigate-app-secure.service=frigate-app
      - traefik.http.routers.frigate-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.frigate-app.loadbalancer.server.port=5000
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    networks: 
      - proxy
    ports:
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    restart: unless-stopped