name: HomeAssistant

volumes:
  ha-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/homeassistant/database      

  ha-mosquitto-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/homeassistant/mosquitto/config

  ha-mosquitto-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/homeassistant/mosquitto/data

  ha-zigbee2mqtt-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/homeassistant/zigbee2mqtt/data

  # ha-whisper-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${DOCKER_ROOT}/homeassistant/whisper/data

  # ha-piper-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${DOCKER_ROOT}/homeassistant/piper/data

  ha-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/homeassistant/config

services:
  ha-mariadb:
    container_name: ha-mariadb
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=homeassistant
      - MYSQL_USER=homeassistant
      - MYSQL_PASSWORD=${DB_USER_PASS}
      - TZ=${TIMEZONE}
    volumes:
      - ha-mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  ha-mqtt:
    container_name: ha-mqtt
    image: eclipse-mosquitto:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - ha-mosquitto-config:/mosquitto/config
      - ha-mosquitto-data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
    environment:
      - TZ=${TIMEZONE}
    labels:
      - "traefik.enable=false"
    restart: unless-stopped

  ha-zigbee2mqtt:
    container_name: ha-zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    security_opt:
      - no-new-privileges:true
    depends_on:
      - ha-mqtt
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ha-zigbee2mqtt-data:/app/data
      - /etc/localtime:/etc/localtime:ro
    # Map local /dev mountpoint to docker
    devices:
      - ${ZIGBEE_DEVICE_MOUNT}:/dev/ttyZigbee
    labels:
      - "traefik.enable=false"
    ports:
      - "8099:8099"
    restart: unless-stopped

  # ha-whisper:
  #   container_name: ha-whisper
  #   image: rhasspy/wyoming-whisper:latest
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - ha-whisper-data:/data
  #     - /etc/localtime:/etc/localtime:ro
  #   command: [ "--model", "tiny-int8", "--language", "en" ]
  #   labels:
  #     - "traefik.enable=false"
  #   ports:
  #     - "10300:10300"
  #   restart: unless-stopped

  # ha-piper:
  #   container_name: ha-piper
  #   image: rhasspy/wyoming-piper:latest
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - ha-piper-data:/data
  #     - /etc/localtime:/etc/localtime:ro
  #   command: [ "--voice", "en_US-lessac-medium" ]
  #   labels:
  #     - "traefik.enable=false"
  #   ports:
  #     - "10200:10200"
  #   restart: unless-stopped

  ha-app:
    container_name: ha-app
    image: homeassistant/home-assistant:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TIMEZONE}
    # Map local /dev mountpoint to docker
    devices:
      - ${RFX_DEVICE_MOUNT}:/dev/ttyRFXtrx
    volumes:
      - ha-config:/config
      - /sys/class/thermal:/sys/class/thermal
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    depends_on:
      - ha-mariadb
      - ha-mqtt
      - ha-zigbee2mqtt
    network_mode: host
    restart: unless-stopped