version: "3"

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  synapse-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matrix/synapse/database
  synapse-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matrix/synapse/data
  synapse-coturn:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matrix/synapse/coturn
  synapse-sliding-sync:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matrix/synapse/sliding-sync

services:
  matrix-synapse-db:
    container_name: matrix-synapse-db
    image: postgres:15-alpine
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=${SYNAPSE_DB_USER}
      - POSTGRES_PASSWORD=${SYNAPSE_DB_USER_PASS}
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - POSTGRES_MULTIPLE_DATABASES=slidingsync:${SLIDING_SYNC_DB_USER}:${SLIDING_SYNC_DB_USER_PASS}
    volumes:
      - synapse-database:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    restart: unless-stopped

  matrix-synapse-redis:
    container_name: matrix-synapse-redis
    image: redis:alpine
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    restart: unless-stopped

  matrix-synapse-app:
    container_name: matrix-synapse-app
    image: ghcr.io/matrix-org/synapse:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - SYNAPSE_SERVER_NAME=${SUBDOMAIN}.${DOMAIN}
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_DATABASE_URL=postgresql://${SYNAPSE_DB_USER}:${SYNAPSE_DB_USER_PASS}@matrix-synapse-db/synapse?sslmode=disable
      - SYNAPSE_REDIS_URL=redis://matrix-synapse-redis:6379
      - SYNAPSE_FEDERATION_ALLOW_FROM_LOOPBACK=true
      - SYNAPSE_FEDERATION_ALLOW_FROM=*
      - UID=1000
      - GID=1000
      - TZ="Europe/Amsterdam"
    ports:
      - "8008:8008/tcp"
      - "8448:8448/tcp"
    volumes:
      - synapse-data:/data
      - /etc/localtime:/etc/localtime:ro
    links:
      - matrix-synapse-db
      - matrix-synapse-redis
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix-synapse-app.entrypoints=http
      - traefik.http.routers.matrix-synapse-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.matrix-synapse-app-secure.entrypoints=https
      - traefik.http.routers.matrix-synapse-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.matrix-synapse-app-secure.tls=true
      - traefik.http.routers.matrix-synapse-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.matrix-synapse-app-secure.service=matrix-synapse-app
      - traefik.http.routers.matrix-synapse-app-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.matrix-synapse-app.loadbalancer.server.port=8008 
    restart: unless-stopped

  matrix-synapse-well-known:
    container_name: matrix-synapse-well-known
    image: nginx:1-alpine
    security_opt:
      - no-new-privileges:true
    volumes:
        - ./well-known:/usr/share/nginx/html/.well-known
        - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix-synapse-well-known.entrypoints=http
      - traefik.http.routers.matrix-synapse-well-known.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/.well-known`)
      - traefik.http.routers.matrix-synapse-well-known-secure.entrypoints=https
      - traefik.http.routers.matrix-synapse-well-known-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/.well-known`)
      - traefik.http.routers.matrix-synapse-well-known-secure.tls=true
      - traefik.http.routers.matrix-synapse-well-known-secure.tls.certresolver=le-dns
      - traefik.http.routers.matrix-synapse-well-known-secure.service=matrix-synapse-well-known
      - traefik.http.routers.matrix-synapse-well-known-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.matrix-synapse-well-known.loadbalancer.server.port=80
    restart: unless-stopped

  matrix-synapse-coturn:
    container_name: matrix-synapse-coturn
    image: instrumentisto/coturn:4
    security_opt:
      - no-new-privileges:true
    environment:
      - TURN_REALM=${SUBDOMAIN}.${DOMAIN}
      - TURN_SECRET=${TURN_SECRET}
      - TURN_SIMPLE_LOG=true
    volumes:
      - synapse-coturn:/var/lib/coturn
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - internal
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
    restart: unless-stopped

  matrix-sliding-sync:
    container_name: matrix-sliding-sync
    image: ghcr.io/matrix-org/sliding-sync:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - SYNCV3_SERVER=https://${SUBDOMAIN}.${DOMAIN}
      - SYNCV3_DB=postgresql://${SLIDING_SYNC_DB_USER}:${SLIDING_SYNC_DB_USER_PASS}@matrix-synapse-db/slidingsync?sslmode=disable
      - SYNCV3_SECRET=${SLIDING_SYNC_SECRET}
      - SYNCV3_BINDADDR=:8008
    volumes:
      - synapse-sliding-sync:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix-sliding-sync.entrypoints=http
      - traefik.http.routers.matrix-sliding-sync.rule=Host(`sliding.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.matrix-sliding-sync-secure.entrypoints=https
      - traefik.http.routers.matrix-sliding-sync-secure.rule=Host(`sliding.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.matrix-sliding-sync-secure.tls=true
      - traefik.http.routers.matrix-sliding-sync-secure.tls.certresolver=le-dns
      - traefik.http.routers.matrix-sliding-sync-secure.service=matrix-sliding-sync
      - traefik.http.routers.matrix-sliding-sync-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.matrix-sliding-sync.loadbalancer.server.port=8008
    restart: unless-stopped
    depends_on:
      - matrix-synapse-db