version: "3"

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  synapse-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matrix/synapse/database
  synapse-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/matrix/synapse/data

services:
  matrix-synapse-app:
    container_name: matrix-synapse-app
    image: matrixdotorg/synapse:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - SYNAPSE_SERVER_NAME=${SUBDOMAIN}.${DOMAIN}
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_DATABASE_URL=postgresql://matrix:matrix@matrix-synapse-db:5432/matrix
      - SYNAPSE_REDIS_URL=redis://matrix-synapse-redis:6379
      # - SYNAPSE_ENABLE_REGISTRATION=true
      - SYNAPSE_FEDERATION_ALLOW_FROM_LOOPBACK=true
      - SYNAPSE_FEDERATION_ALLOW_FROM=*
      - UID=1000
      - GID=1000
      - TZ="Europe/Amsterdam"
    ports:
      - "8008:8008"
    volumes:
      - synapse-data:/data
      - /etc/localtime:/etc/localtime:ro
    links:
      - matrix-synapse-db
      - matrix-synapse-redis
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix-synapse-app.entrypoints=http
      - traefik.http.routers.matrix-synapse-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.matrix-synapse-app-secure.entrypoints=https
      - traefik.http.routers.matrix-synapse-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.matrix-synapse-app-secure.tls=true
      - traefik.http.routers.matrix-synapse-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.matrix-synapse-app-secure.service=matrix-synapse-app
      - traefik.http.routers.matrix-synapse-app-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.matrix-synapse-app.loadbalancer.server.port=8008 
    restart: always

  # Uncomment if you don't want federation
  matrix-synapse-well-known:
    container_name: matrix-synapse-well-known
    image: nginx:latest
    security_opt:
      - no-new-privileges:true
    volumes:
        - ./well-known:/usr/share/nginx/html/.well-known
        - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix-synapse-well-known.entrypoints=http
      - traefik.http.routers.matrix-synapse-well-known.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/.well-known`)
      - traefik.http.routers.matrix-synapse-well-known-secure.entrypoints=https
      - traefik.http.routers.matrix-synapse-well-known-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/.well-known`)
      - traefik.http.routers.matrix-synapse-well-known-secure.tls=true
      - traefik.http.routers.matrix-synapse-well-known-secure.tls.certresolver=le-dns
      - traefik.http.routers.matrix-synapse-well-known-secure.service=matrix-synapse-well-known
      - traefik.http.routers.matrix-synapse-well-known-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.matrix-synapse-well-known.loadbalancer.server.port=80

  matrix-synapse-db:
    container_name: matrix-synapse-db
    image: postgres:alpine
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASS}
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse-database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    restart: always

  matrix-synapse-redis:
    container_name: matrix-synapse-redis
    image: redis:alpine
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    restart: always