version: '3'

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  librespeed-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/librespeed/config
  librespeed-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/librespeed/database/

services:
  librespeed-db:
    container_name: librespeed-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=librespeed
      - MYSQL_USER=librespeed
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - librespeed-database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  librespeed-app:
    container_name: librespeed-app
    image: ghcr.io/linuxserver/librespeed:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - PASSWORD=${RESULTS_PASS}
      - DB_TYPE=mysql
      - DB_NAME=librespeed
      - DB_HOSTNAME=librespeed-db
      - DB_USERNAME=librespeed
      - DB_PASSWORD=${DB_USER_PASS}
    volumes:
      - librespeed-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed-app.entrypoints=http"
      - "traefik.http.routers.librespeed-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.librespeed-app.middlewares=secured@file"
      - "traefik.http.routers.librespeed-app-secure.entrypoints=https"
      - "traefik.http.routers.librespeed-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.librespeed-app-secure.tls=true"
      - "traefik.http.routers.librespeed-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.librespeed-app-secure.service=librespeed-app"
      - "traefik.http.services.librespeed-app.loadbalancer.server.port=80"
    depends_on:
      - librespeed-db
    networks: 
      - internal
      - proxy
    # # Used for SSH remoteForward
    # ports:
    #   - 4007:80
    restart: unless-stopped