name: DrawIO

networks:
    proxy:
      name: proxy
      external: true
    internal:
      internal: true

services:
  drawio-app:
    container_name: drawio-app
    image: jgraph/drawio
    security_opt:
      - no-new-privileges:true
    environment:
      PUBLIC_DNS: ${SUBDOMAIN}.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio-app-secure.entrypoints=websecure
      - traefik.http.routers.drawio-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.drawio-app-secure.tls=true
      - traefik.http.routers.drawio-app-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.drawio-app-secure.service=drawio-app
      - traefik.http.routers.drawio-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.drawio-app.loadbalancer.server.port=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - internal
      - proxy
    restart: unless-stopped
