name: nzbget

networks:
  proxy:
    name: proxy
    external: true

volumes:
  nzbget-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/nzbget/config
  nzbget-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads 

services:
  nzbget:
    container_name: nzbget
    image: ghcr.io/linuxserver/nzbget:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - nzbget-config:/config
      - nzbget-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.nzbget-secure.entrypoints=websecure
      - traefik.http.routers.nzbget-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.nzbget-secure.tls=true
      - traefik.http.routers.nzbget-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.nzbget-secure.service=nzbget
      - traefik.http.routers.nzbget-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.nzbget.loadbalancer.server.port=6789
    networks:
      - proxy
    restart: unless-stopped