version: "2.1"

volumes:
  nzbget-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/nzbget/config
  nzbget-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/downloads 

services:
  nzbget:
    container_name: nzbget
    image: ghcr.io/linuxserver/nzbget:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - nzbget-config:/config
      - nzbget-downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:expressvpn
    restart: unless-stopped