version: "3.3"

networks:
  proxy:
    external: 
      name: proxy
  internal:
    internal: true

services:
  matomo-db:
    container_name: "matomo-db"
    image: "mariadb"
    security_opt:
      - no-new-privileges:true
    command: --max-allowed-packet=64MB
    volumes:
      - ${DOCKER_ROOT}/matomo/matomo-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MYSQL_PASSWORD=${DB_USER_PASS}
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  matomo-app:
    container_name: "matomo-app"
    image: "matomo:fpm-alpine"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - matomo-db
    volumes:
      - ${DOCKER_ROOT}/matomo/config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo-app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=${DB_USER_PASS}
      - MATOMO_DATABASE_DBNAME=matomo

  matomo-nginx:
    container_name: "matomo-nginx"
    image: "nginx:alpine"
    restart: unless-stopped
    volumes:
      - matomo-app:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo-nginx.entrypoints=http"
      - "traefik.http.routers.matomo-nginx.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.matomo-nginx.middlewares=secured@file"
      - "traefik.http.routers.matomo-nginx-secure.entrypoints=https"
      - "traefik.http.routers.matomo-nginx-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.matomo-nginx-secure.tls=true"
      - "traefik.http.routers.matomo-nginx-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.matomo-nginx-secure.service=matomo-nginx"
      - "traefik.http.services.matomo-nginx.loadbalancer.server.port=80"
    networks:
      - proxy
      - internal

volumes:
  matomo-db:
  matomo-app:
