version: '3'

networks:
  proxy:
    external: 
      name: proxy

volumes:
  syncthing-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/syncthing/config
  syncthing-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STORAGE_ROOT}/syncthing

services:
  syncthing-app:
    container_name: syncthing-app
    image: ghcr.io/linuxserver/syncthing:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - syncthing-config:/config
      - syncthing-data:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing-app.entrypoints=http"
      - "traefik.http.routers.syncthing-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.syncthing-app.middlewares=secured@file"
      - "traefik.http.routers.syncthing-app-secure.entrypoints=https"
      - "traefik.http.routers.syncthing-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.syncthing-app-secure.tls=true"
      - "traefik.http.routers.syncthing-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.syncthing-app-secure.service=syncthing-app"
      - "traefik.http.services.syncthing-app.loadbalancer.server.port=8384"
    networks: 
      - proxy
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped