version: '3.3'

networks:
  proxy:
    name: proxy
    external: true

volumes:
  nginx-static-public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/nginx-static/${COMPOSE_PROJECT_NAME}/public

services:

  nginx-static-app:
    container_name: "nginx-static-${COMPOSE_PROJECT_NAME}"
    image: "flashspys/nginx-static"
    security_opt:
      - no-new-privileges:true
    volumes:
      - nginx-static-public:/static
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-static-${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure
      - traefik.http.routers.nginx-static-${COMPOSE_PROJECT_NAME}-nginx-secure.rule=Host(`${SITE_URL}`) || Host(`www.${SITE_URL}`)
      - traefik.http.routers.nginx-static-${COMPOSE_PROJECT_NAME}-secure.tls=true
      - traefik.http.routers.nginx-static-${COMPOSE_PROJECT_NAME}-secure.tls.certresolver=le-dns
      - traefik.http.routers.nginx-static-${COMPOSE_PROJECT_NAME}-secure.service=nginx-static-${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.nginx-static-${COMPOSE_PROJECT_NAME}-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.nginx-static-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80
    networks:
      - proxy
    restart: unless-stopped
