version: "3.7"

networks:
  proxy:
    external: 
      name: proxy

services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-alpine
    security_opt:
      - no-new-privileges:true
    pid: host
    environment:
      - GLANCES_OPT=-w
    volumes:
      - ./glances.conf:/glances/conf/glances.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances-app.entrypoints=http"
      - "traefik.http.routers.glances-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.glances-app.middlewares=secured@file"
      - "traefik.http.routers.glances-app-secure.entrypoints=https"
      - "traefik.http.routers.glances-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.glances-app-secure.tls=true"
      - "traefik.http.routers.glances-app-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.glances-app-secure.service=glances-app"
      - "traefik.http.services.glances-app.loadbalancer.server.port=61208"
    networks:
      - proxy
    restart: unless-stopped