name: Minecraft-Server-Java

# networks:
#   proxy:
#     name: proxy
#     external: true

volumes:
  minecraft-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/minecraft-server/java/data

services:
  minecraft-java-server:
    container_name: minecraft-java-server
    image: itzg/minecraft-server:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - 25565:25565
    environment:
      UID: ${PUID}
      GID: ${PGID}
      EULA: "TRUE"
      SERVER_NAME: ${SERVER_NAME}
      MODE: ${GAME_MODE}
      DIFFICULTY: ${DIFFICULTY}
      MEMORY: 4G
      ONLINE_MODE: ${ONLINE_MODE}
      LEVEL: ${ACTIVE_WORLD}
    volumes:
      - minecraft-data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
