version: '3'

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  paperless-ngx-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/paperless-ngx/config
  paperless-ngx-data:
    driver: local
    driver_opts:
      type: ${MEDIA_DRIVER_OPT_TYPE}
      o: ${MEDIA_DRIVER_OPT_O}
      device: ${DOCUMENTS_PATH}

services:
  paperless-ngx-app:
    container_name: paperless-ngx-app
    image: lscr.io/linuxserver/paperless-ngx:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - paperless-ngx-config:/config
      - paperless-ngx-data:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.paperless-ngx-app.entrypoints=http
      - traefik.http.routers.paperless-ngx-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.paperless-ngx-app-secure.entrypoints=https
      - traefik.http.routers.paperless-ngx-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.paperless-ngx-app-secure.tls=true
      - traefik.http.routers.paperless-ngx-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.paperless-ngx-app-secure.service=paperless-ngx-app
      - traefik.http.routers.paperless-ngx-app-secure.middlewares=https_redirect@docker,non_www@docker,sec_headers@docker,gzip_compress@docker
      - traefik.http.services.paperless-ngx-app.loadbalancer.server.port=8000
    networks: 
      - internal
      - proxy
    restart: unless-stopped