name: freshrss

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  freshrss-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/freshrss/config
  freshrss-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/freshrss/database/

services:
  freshrss-db:
    container_name: freshrss-db
    hostname: freshrss-db
    image: postgres:18-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss-database:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    environment:
      POSTGRES_DB: freshrss
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: ${DB_PASS}
    command:
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=32MB
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U freshrss -d freshrss
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  freshrss-app:
    container_name: freshrss-app
    image: ghcr.io/linuxserver/freshrss:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - freshrss-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss-app-secure.entrypoints=websecure
      - traefik.http.routers.freshrss-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.freshrss-app-secure.tls=true
      - traefik.http.routers.freshrss-app-secure.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.freshrss-app-secure.service=freshrss-app
      - traefik.http.routers.freshrss-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file
      - traefik.http.services.freshrss-app.loadbalancer.server.port=80
    depends_on:
      freshrss-db:
        condition: service_healthy
    networks:
      - internal
      - proxy
    restart: unless-stopped
