version: '3'

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  freshrss-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/freshrss/config
  freshrss-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/freshrss/database/

services:
  freshrss-db:
    container_name: freshrss-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=freshrss
      - MYSQL_USER=freshrss
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - freshrss-database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  freshrss-app:
    container_name: freshrss-app
    image: ghcr.io/linuxserver/freshrss:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
    volumes:
      - freshrss-config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss-app.entrypoints=web
      - traefik.http.routers.freshrss-app.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.freshrss-app-secure.entrypoints=websecure
      - traefik.http.routers.freshrss-app-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.freshrss-app-secure.tls=true
      - traefik.http.routers.freshrss-app-secure.tls.certresolver=le-dns
      - traefik.http.routers.freshrss-app-secure.service=freshrss-app
      - traefik.http.routers.freshrss-app-secure.middlewares=https-redirect@file,non-www@file,secure-headers@file,gzip-compress@file,basic-auth@file
      - traefik.http.services.freshrss-app.loadbalancer.server.port=80
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect@file
    depends_on:
      - freshrss-db
    networks: 
      - internal
      - proxy
    # # Used for SSH remoteForward
    # ports:
    #   - 4007:80
    restart: unless-stopped