version: "3.3"

networks:
  proxy:
    external: 
      name: proxy

services:
  tokentracker-app:
    container_name: tokentracker-app
    image: xblackbytesx/tokentracker:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tokentracker.entrypoints=http"
      - "traefik.http.routers.tokentracker.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.tokentracker.middlewares=secured@file"
      - "traefik.http.routers.tokentracker-secure.entrypoints=https"
      - "traefik.http.routers.tokentracker-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.tokentracker-secure.tls=true"
      - "traefik.http.routers.tokentracker-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.tokentracker-secure.service=tokentracker"
      - "traefik.http.services.tokentracker.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped