version: "3.3"

networks:
  proxy:
    name: proxy
    external: true
  internal:
    internal: true

volumes:
  wordpress:
  wordpress-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/database/
  wordpress-plugins:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/plugins
  wordpress-themes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/themes
  wordpress-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/uploads

services:
  wp-db:
    container_name: wp-${COMPOSE_PROJECT_NAME}-db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASS}
    volumes:
      - wordpress-database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 15s
      retries: 30
    restart: unless-stopped

  wp-app:
    container_name: "wp-${COMPOSE_PROJECT_NAME}-app"
    image: "wordpress:php8.0-fpm-alpine"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wp-db
    environment:
      - WORDPRESS_DB_HOST=wp-db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_USER_PASS}
    volumes:
      - wordpress:/var/www/html
      - wordpress-plugins:/var/www/html/wp-content/plugins/
      - wordpress-themes:/var/www/html/wp-content/themes/
      - wordpress-uploads:/var/www/html/wp-content/uploads/
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=false"
    networks:
      - proxy
      - internal
    restart: unless-stopped


  wp-nginx:
    container_name: "wp-${COMPOSE_PROJECT_NAME}-nginx"
    image: "nginx:alpine"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wp-app
    networks:
      - internal
      - proxy
    volumes:
      - wordpress:/var/www/html:ro
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/plugins:/var/www/html/wp-content/plugins/:ro
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/themes:/var/www/html/wp-content/themes/:ro
      - ${DOCKER_ROOT}/wordpress/${COMPOSE_PROJECT_NAME}/uploads:/var/www/html/wp-content/uploads/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx.entrypoints=http"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx.rule=Host(`${BLOG_URL}`, `www.${BLOG_URL}`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.strip-www.redirectregex.regex=^https?://www.`${BLOG_URL}`"
      - "traefik.http.middlewares.strip-www.redirectregex.replacement=https://`${BLOG_URL}`"
      - "traefik.http.middlewares.sec-headers.headers.framedeny=true"
      - "traefik.http.middlewares.sec-headers.headers.browserxssfilter=true"
      - "traefik.http.middlewares.sec-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.sec-headers.headers.stsseconds=31536000"
      - "traefik.http.middlewares.sec-headers.headers.stspreload=true"
      - "traefik.http.middlewares.sec-headers.headers.forcestsheader=true"
      - "traefik.http.middlewares.sec-headers.headers.customframeoptionsvalue=`SAMEORIGIN`"
      - "traefik.http.middlewares.gzip-compress.compress=true"
      - "traefik.http.middlewares.middleware-chain.chain.middlewares=redirect-to-https,strip-www,sec-headers,gzip-compress"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx-secure.entrypoints=https"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx-secure.rule=Host(`${BLOG_URL}`, `www.${BLOG_URL}`)"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx-secure.tls=true"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx-secure.middlewares=middleware-chain"
      - "traefik.http.routers.wp-${COMPOSE_PROJECT_NAME}-nginx-secure.service=wp-${COMPOSE_PROJECT_NAME}-nginx"
      - "traefik.http.services.wp-${COMPOSE_PROJECT_NAME}-nginx.loadbalancer.server.port=80"
    restart: unless-stopped

  # wp-redis:
  #   container_name: wp-${COMPOSE_PROJECT_NAME}-redis
  #   image: redis:alpine
  #   security_opt:
  #     - no-new-privileges:true
  #   networks: 
  #     - internal
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #   labels:
  #     - "traefik.enable=false"
  #   restart: unless-stopped